version: '2.2'

services:
  # db:
  #   image: mariadb:10.5
  #   container_name: db
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - /home/chaekim/data:/var/lib/mysql
  #   environment:
  #     MARIADB_ROOT_PASSWORD: wordpress
  #     MARIADB_DATABASE: wordpress
  #     MARIADB_USER: wordpress
  #     MARIADB_PASSWORD: wordpress
  #   networks:
  #     - inception

  # wordpress:
  #   depends_on:
  #     - db
  #   # build:
  #   #   dockerfile: ./
  #   image: wordpress:latest
  #   container_name: wordpress
  #   ports:
  #     - "9000:9000"
  #   # restart: always
  #   volumes:
  #     - ./requirements/wordpress/tools:/var/www/html
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_NAME: wordpress
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: wordpress
  #   networks:
  #     - inception

  nginx:
    # depends_on:
    #   - wordpress
    # build:
    #   dockerfile: ./
    image: nginx:test
    container_name: nginx
    # volumes:
    #   - ./requirements/wordpress/tools:/var/www/html
      # - ./requirements/nginx/conf:/etc/nginx/conf.d
    # volumes:
    #   - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    #   - ./data/certbot/conf:/etc/letsencrypt
    #   - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      # - 443:443
    networks:
      - inception

networks:
  inception:
    driver: bridge


  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   networks:
  #     - inception